name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH key
      run: |
        echo "${{ secrets.EC2_KEY }}" > ec2_key.pem
        chmod 400 ec2_key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} << 'EOF'
          APP_DIR="/home/ubuntu/devshop"

          if [ ! -d "$APP_DIR/.git" ]; then
            echo "Cloning fresh repo into $APP_DIR"
            rm -rf "$APP_DIR"
            git clone https://github.com/aoalaka/devshop.git "$APP_DIR"
          else
            echo "Repo already exists. Pulling latest changes..."
            cd "$APP_DIR"
            git pull origin main
          fi

          cd "$APP_DIR"
          npm install
          pm2 restart devshop || pm2 start app.js --name devshop
        EOF
